language: node_js
sudo: required
dist: trusty
node_js:
  - "8"
cache:
  directories:
    - $HOME/.npm
install:
  - npm install
script:
  - npm run lint
  - npm run test:coverage
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"