// <div class="RadCalendarPopup RadCalendarPopupShadows" style="position: absolute; border: 0px none; z-index: 5002; left: 1733px; top: 345px;"><div id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar" class="RadCalendar RadCalendar_Silk" style="" role="grid" aria-atomic="true" aria-labelledby="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_Title">
//                      <div class="rcTitlebar">
//                          <a id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_FNP" class="t-button rcFastPrev" title="<<" aria-label="<<" href="#" tabindex="-1" role="presentation"><span class="t-font-icon t-i-arrow-double-60-left"></span></a><a id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_NP" class="t-button rcPrev" title="<" aria-label="<" href="#" tabindex="-1" role="presentation"><span class="t-font-icon t-i-arrow-left"></span></a><div class="rcNextButtons">
//                              <a id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_NN" class="t-button rcNext" title=">" aria-label=">" href="#" tabindex="-1" role="presentation"><span class="t-font-icon t-i-arrow-right"></span></a><a id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_FNN" class="t-button rcFastNext" title=">>" aria-label=">>" href="#" tabindex="-1" role="presentation"><span class="t-font-icon t-i-arrow-double-60-right"></span></a>
//                          </div><span id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_Title" class="rcTitle" aria-live="assertive">November, 2018</span>
//                      </div><div class="rcMain">
//                          <table id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_Top" class="rcMainTable" summary="Table containing all dates for the currently selected month." tabindex="100">
//                              <caption>
//                                  <span style="display:none;">November, 2018</span>
//                              </caption><thead>
//                                  <tr class="rcWeek" role="row">
//                                      <th class="rcViewSel" scope="col" role="columnheader"><span style="display:none">week</span></th><th id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_Top_cs_1" title="Sunday" scope="col" abbr="Sun" role="columnheader">S</th><th id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_Top_cs_2" title="Monday" scope="col" abbr="Mon" role="columnheader">M</th><th id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_Top_cs_3" title="Tuesday" scope="col" abbr="Tue" role="columnheader">T</th><th id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_Top_cs_4" title="Wednesday" scope="col" abbr="Wed" role="columnheader">W</th><th id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_Top_cs_5" title="Thursday" scope="col" abbr="Thu" role="columnheader">T</th><th id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_Top_cs_6" title="Friday" scope="col" abbr="Fri" role="columnheader">F</th><th id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_Top_cs_7" title="Saturday" scope="col" abbr="Sat" role="columnheader">S</th>
//                                  </tr>
//                              </thead><tbody>
//                                  <tr class="rcRow" role="row">
//                                      <th id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_Top_rs_1" scope="row" role="rowheader">44</th><td class="rcOtherMonth" title="Sunday, October 28, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">28</a></td><td class="rcOtherMonth" title="Monday, October 29, 2018" role="gridcell" style=""><a href="#" tabindex="-1" role="presentation">29</a></td><td class="rcOtherMonth" title="Tuesday, October 30, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">30</a></td><td class="rcOtherMonth" title="Wednesday, October 31, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">31</a></td><td title="Thursday, November 01, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">1</a></td><td title="Friday, November 02, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">2</a></td><td class="rcWeekend" title="Saturday, November 03, 2018" role="gridcell" style=""><a href="#" tabindex="-1" role="presentation">3</a></td>
//                                  </tr><tr class="rcRow" role="row">
//                                      <th id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_Top_rs_2" scope="row" role="rowheader">45</th><td class="rcWeekend" title="Sunday, November 04, 2018" role="gridcell" style=""><a href="#" tabindex="-1" role="presentation">4</a></td><td title="Monday, November 05, 2018" role="gridcell" class="" style=""><a href="#" tabindex="-1" role="presentation">5</a></td><td title="Tuesday, November 06, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">6</a></td><td title="Wednesday, November 07, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">7</a></td><td title="Thursday, November 08, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">8</a></td><td title="Friday, November 09, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">9</a></td><td class="rcWeekend" title="Saturday, November 10, 2018" role="gridcell" style=""><a href="#" tabindex="-1" role="presentation">10</a></td>
//                                  </tr><tr class="rcRow" role="row">
//                                      <th id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_Top_rs_3" scope="row" role="rowheader">46</th><td class="rcWeekend" title="Sunday, November 11, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">11</a></td><td title="Monday, November 12, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">12</a></td><td title="Tuesday, November 13, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">13</a></td><td title="Wednesday, November 14, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">14</a></td><td title="Thursday, November 15, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">15</a></td><td title="Friday, November 16, 2018" role="gridcell" class="rcFocus "><a href="#" tabindex="0" role="presentation">16</a></td><td class="rcWeekend" title="Saturday, November 17, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">17</a></td>
//                                  </tr><tr class="rcRow" role="row">
//                                      <th id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_Top_rs_4" scope="row" role="rowheader">47</th><td class="rcWeekend" title="Sunday, November 18, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">18</a></td><td title="Monday, November 19, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">19</a></td><td title="Tuesday, November 20, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">20</a></td><td title="Wednesday, November 21, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">21</a></td><td title="Thursday, November 22, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">22</a></td><td title="Friday, November 23, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">23</a></td><td class="rcWeekend" title="Saturday, November 24, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">24</a></td>
//                                  </tr><tr class="rcRow" role="row">
//                                      <th id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_Top_rs_5" scope="row" role="rowheader">48</th><td class="rcWeekend" title="Sunday, November 25, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">25</a></td><td title="Monday, November 26, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">26</a></td><td title="Tuesday, November 27, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">27</a></td><td title="Wednesday, November 28, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">28</a></td><td title="Thursday, November 29, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">29</a></td><td title="Friday, November 30, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">30</a></td><td class="rcOtherMonth" title="Saturday, December 01, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">1</a></td>
//                                  </tr><tr class="rcRow" role="row">
//                                      <th id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_Top_rs_6" scope="row" role="rowheader">49</th><td class="rcOtherMonth" title="Sunday, December 02, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">2</a></td><td class="rcOtherMonth" title="Monday, December 03, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">3</a></td><td class="rcOtherMonth" title="Tuesday, December 04, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">4</a></td><td class="rcOtherMonth" title="Wednesday, December 05, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">5</a></td><td class="rcOtherMonth" title="Thursday, December 06, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">6</a></td><td class="rcOtherMonth" title="Friday, December 07, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">7</a></td><td class="rcOtherMonth" title="Saturday, December 08, 2018" role="gridcell"><a href="#" tabindex="-1" role="presentation">8</a></td>
//                                  </tr>
//                              </tbody>
//                          </table>
//                      </div><input name="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_SD" id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_SD" value="[]" type="hidden"><input name="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_AD" id="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_AD" value="[[1980,1,1],[2099,12,30],[2018,11,16]]" type="hidden">
//                  </div></div>


//                  <div id="datepicker-wrapper" title="Date input" class="RadInput RadInput_Silk" role="textbox" aria-atomic="true" aria-disabled="false" aria-valuemax="12/31/2099 0:0:0" aria-valuemin="1/1/1980 0:0:0">
//              <input id="datepicker-input" name="datepicker-input" class="riTextBox riEnabled" title="Date input" type="text"><div class="rcSelect" role="presentation">
//                  <a aria-label="Open the calendar popup." title="Open the calendar popup." href="#" id="ctl00_ContentPlaceholder1_RadDatePicker1_popupButton" class="rcCalPopup" role="button" aria-controls="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_wrapper"></a>
//              </div><input id="ctl00_ContentPlaceholder1_RadDatePicker1_dateInput_ClientState" name="ctl00_ContentPlaceholder1_RadDatePicker1_dateInput_ClientState" autocomplete="off" value="{&quot;enabled&quot;:true,&quot;emptyMessage&quot;:&quot;&quot;,&quot;validationText&quot;:&quot;&quot;,&quot;valueAsString&quot;:&quot;&quot;,&quot;minDateStr&quot;:&quot;1980-01-01-00-00-00&quot;,&quot;maxDateStr&quot;:&quot;2099-12-31-00-00-00&quot;,&quot;lastSetTextBoxValue&quot;:&quot;&quot;}" type="hidden">
//          </div>


import React from 'react';

class DatePicker extends React.Component {
    render() {
        return (
            <div id="datepicker-wrapper" title="Date input" className="RadInput RadInput_Silk" role="textbox" aria-atomic="true" aria-disabled="false" aria-valuemax="12/31/2099 0:0:0" aria-valuemin="1/1/1980 0:0:0">
                <input id="datepicker-input" name="datepicker-input" className="riTextBox riEnabled" title="Date input" type="text" />
                <div className="rcSelect" role="presentation">
                    <a aria-label="Open the calendar popup." title="Open the calendar popup." href="#" id="ctl00_ContentPlaceholder1_RadDatePicker1_popupButton" className="rcCalPopup" role="button" aria-controls="ctl00_ContentPlaceholder1_RadDatePicker1_calendar_wrapper" />
                </div>
            </div>
        );
    }
}
